### ISSUE TITLE
Downloading files to incorrect location?

### ISSUE THREAD

**Issue by Ackthbpt** [bdwinanto/sonarr_yt-dlp#2]
My `docker-compose.yml` file looks like this:

```
  sonarr_yt-dlp:
    image: bdwinanto/sonarr_yt-dlp:latest
    container_name: sonarr_yt-dlp
    volumes:
      - /mnt/data/appdata/sonarr_yt-dlp:/config
      - /mnt/data/media/tvshows:/sonarr_root
      - /mnt/data/appdata/sonarr_yt-dlp/logs:/logs
```

Here is my `config.yml`:
```
sonarrytdl:
    scan_interval: 1
    debug: true
sonarr:
    host: 192.168.1.226
    port: 8989
    apikey: [REDACTED]
    ssl: false
ytdl:
    default_format: bestvideo[height<=1080]+bestaudio/best[height<=1080]
series:
  - title: Defunctland
    url: https://www.youtube.com/c/Defunctland/
```
However, in the `sonarr_youtubedl.log` I show lots of the following:
```
sonarr_youtubedl - DEBUG - {'format': 'bestvideo[height<=1080]+bestaudio/best[height<=1080]', 'quiet': False, 'merge-output-format': 'mp4', 'outtmpl': '/sonarr_root/data/media/tvshows/Defunctland/Season 1/Defunctland - S1E25 - Unused and New Footage of Extinct Attractions WEBDL.%(ext)s', 'progress_hooks': [<function ytdl_hooks_debug at 0x7f36018f2830>], 'noplaylist': True, 'logger': <utils.YoutubeDLLogger object at 0x7f360130d330>}
```
Note how it's saving to `/sonarr_root/data/media/tvshows/` rather than just `/sonarr_root/`?  It's appending one onto the other.

Am I doing something dumb, or is this a bug?
